export ZSH=$HOME/.oh-my-zsh

# use vim as the visual editor
export VISUAL='mate -w'
export EDITOR=vim

# ensure dotfiles bin directory is loaded first
export PATH="$HOME/.bin:/usr/local/sbin:$PATH"
export PATH="$HOME/.rvm/bin:$PATH" # Add RVM to PATH for scripting
export PATH="$HOME/.nenv/bin:$HOME/.nenv/shims:$PATH" # Add NENV to PATH for scripting
export PATH="$ZSH/bin:$PATH"

export WORKSPACE="$HOME/Documents/workspace/"
export GOPATH="$WORKSPACE/gopath/"

export PATH=$PATH:$GOPATH/bin

# Fix PIP's annoying "ValueError: unknown locale: UTF-8"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Local config
[[ -f ~/.zshenv.local ]] && source ~/.zshenv.local
