export ZSH=$HOME/.oh-my-zsh

# use vim as the visual editor
export VISUAL='mate -w'
export EDITOR=code
export KUBE_EDITOR='code --wait'

# ensure dotfiles bin directory is loaded first

export PATH="$HOME/.bin:/usr/local/sbin:$PATH"
export PATH="$ZSH/bin:$PATH"

export PATH="$PATH:$GOPATH/bin:$HOME/go/bin/"
export PATH="$PATH:$HOME/.poetry/bin"
export PATH="$PATH:$HOME/jetbrains"
export PATH="$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin"

export WORKSPACE="$HOME/Workspace"

# Fix PIP's annoying "ValueError: unknown locale: UTF-8"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Pipenv
export PIPENV_VENV_IN_PROJECT=1

# Local config
[[ -f ~/.zshenv.local ]] && source ~/.zshenv.local
