# use vim as the visual editor
export VISUAL='mate -w'
export EDITOR=vim

# ensure dotfiles bin directory is loaded first
export PATH="$HOME/.bin:/usr/local/sbin:$PATH"
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

export WORKSPACE="$HOME/Documents/workspace/"

# Fix PIP's annoying "ValueError: unknown locale: UTF-8"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Local config
[[ -f ~/.zshenv.local ]] && source ~/.zshenv.local
